Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -7,7 +7,7 @@ jobs:
   greet:
     runs-on: ubuntu-latest
     steps:
-    - name: Tell us tests passed
-      run: echo "Tests passed"
-    - name: Pass tests
-      run: exit 0
+    - name: Tell us tests failed
+      run: echo "Tests failed"
+    - name: Tests failed
+      run: exit 1
